# Generated by Django 6.0.4 on 2026-05-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_person_movie_cast_movie_crew'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='character_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
