# Generated by Django 6.0.4 on 2026-05-17 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_person_character_name_person_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='role',
        ),
    ]
