# Generated by Django 6.0.4 on 2026-05-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_movie_crew_alter_movie_title_moviecrew'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='crew',
            field=models.ManyToManyField(blank=True, related_name='crew_credits', through='movies.MovieCrew', to='movies.person'),
        ),
    ]
