# Generated by Django 6.0.4 on 2026-05-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_remove_movie_cast_moviecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(blank=True, related_name='acting_credits', through='movies.MovieCast', to='movies.person'),
        ),
    ]
