# Generated by Django 6.0.4 on 2026-05-17 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_person_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='character_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='role',
        ),
    ]
