# Generated by Django 6.0.4 on 2026-05-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watched_by', to='movies.movie'),
        ),
    ]
