# Generated by Django 6.0.4 on 2026-05-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_profile_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_movies',
        ),
    ]
