# Generated by Django 6.0.4 on 2026-05-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_alter_review_options_remove_review_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='has_profile',
            field=models.BooleanField(default=False),
        ),
    ]
