# Generated by Django 6.0.4 on 2026-05-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_person_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
