# Generated by Django 6.0.4 on 2026-05-23 18:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_movie_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='movie_watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
